// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfxbkzsstlyuckgnaoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmeGJrenNzdGx5dWNrZ25hb2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTQ3NDgsImV4cCI6MjA3MTA5MDc0OH0.RfsCG9Vj6ENVtKhy69GHY-qmGjj9ZEIxnH45sk51Ixo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});